version: '3.8'

services:
  qumulo-be:
    build: .
    container_name: qumulo-be
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: qumulo-db
    environment:
      POSTGRES_USER: qumulo
      POSTGRES_PASSWORD: qumulo_password
      POSTGRES_DB: qumulo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
